Add testing methodology
P3K-TEAM/documents pull request #4
Opened 2020-11-20 12:30 UTC by KToldy

Add testing methodology + output pdf file

2020-11-20 12:45 UTC, MCFreddie777 requested changes, later dismissed
Left some comments, otherwise LGTM.

2020-11-20 12:45 UTC, MCFreddie777 commented on src/metodiky/metodika-testovania.tex
> +				   \section*{End to End testy \(E2E\)}
"E2E Testy" is sufficient.

2020-11-20 12:45 UTC, MCFreddie777 commented on src/metodiky/metodika-testovania.tex
> +		\section*{UNIT testy}
No need for caps... Just `Unit testy`

2020-11-20 12:45 UTC, MCFreddie777 commented on src/metodiky/metodika-testovania.tex
> +Unit testy sú uložené v adresári \/tests\/unit, v ktorom je na každý komponent vytvorený samostatný test. Pomenovanie jednotlivých testov musí dodržiavať menovaciu konvenciu *.spec.js.
seems like the escaping did not work in the result doc

2020-11-20 13:41 UTC, MaliniakovaKarin approved these changes, later dismissed

2020-11-20 14:00 UTC, MaliniakovaKarin commented on src/metodiky/metodika-testovania.tex
> +Každá nová funkcionalita systému, ktorá bola implementovaná, musí prejsť testovaním. Testy sa vyvárajú jednotkové, ale aj integračné, pričom testy musia pokrývať aj určitú časť funkcionality.
"vyvárajú" change "vytvárajú"

2020-11-20 14:03 UTC, MaliniakovaKarin commented on src/metodiky/metodika-testovania.tex
> +\item Napísanie kódu, ktorý sa bude testovať.
change sentences like this: "Napíš kód, ktorý sa bude testovať"

2020-11-20 14:19 UTC, MaliniakovaKarin submitted a review, later dismissed

2020-11-26 10:23 UTC, MaliniakovaKarin approved these changes

2020-11-26 10:24 UTC, merged